[package]
name = "beekeeper"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = "2.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.8", features = ["json"] }
argon2 = "0.5.3"
static_init = "1.0.3"
actix-web = "4.9.0"
serde_json = "1.0.128"
thiserror = "1.0.64"
lettre = "0.11.9"

[dev-dependencies]
mockall = "0.13.0"



[features]
actix = []

default = ["actix"]
